name: Waka Readme

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches: [master]

jobs:
  update-waka:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-github:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub README Generator
        uses: th3c0d3br34ker/github-readme-info@1.0.2
